# Generated by Django 5.0.7 on 2024-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_created_at_listing_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_listings',
            field=models.ManyToManyField(blank=True, related_name='followers', to='auctions.listing'),
        ),
    ]
